export enum NotificationType {
  SYSTEM = "SYSTEM",
  DEVICE_PAIRING = "DEVICE_PAIRING",
  PLAYBACK_HANDOFF = "PLAYBACK_HANDOFF",
  CREATOR_PULSE = "CREATOR_PULSE",
  SOCIAL_PUMP = "SOCIAL_PUMP",
  SOCIAL_PATTER = "SOCIAL_PATTER",
  DOWNLOAD_STATUS = "DOWNLOAD_STATUS",
}
